on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Yarn install
        run: yarn install --frozen-lockfile

      - name: Nuxt build
        run: yarn run build

      - name: Containerify
        run: |
          yarn containerify --folder . \
            --to ghcr.io/${{ github.repository }}:latest \
            --toToken ${{ secrets.GITHUB_TOKEN }}
